spring:
  application:
    name: eureka

server:
  port: 8080

eureka:
  instance:
    hostname: localhost # Because use single eureka server
  client:
    fetch-registry: false # Single eureka server need
    register-with-eureka: false # Single eureka server need

#---
#spring:
#  application:
#    name: eureka
#  profiles: server1
#
#server:
#  port: 8000
#
#eureka:
#  instance:
#    hostname: server1
#    prefer-ip-address: false
#  client:
#    service-url:
#      defaultZone: http://server2:8001/eureka, http://server3:8002/eureka
#
#---
#spring:
#  application:
#    name: eureka
#  profiles: server2
#
#server:
#  port: 8001
#
#eureka:
#  instance:
#    hostname: server2
#    prefer-ip-address: false
#  client:
#    service-url:
#      defaultZone: http://server1:8000/eureka, http://server3:8002/eureka
#
#---
#spring:
#  application:
#    name: eureka
#  profiles: server3
#
#server:
#  port: 8002
#
#eureka:
#  instance:
#    hostname: server3
#    prefer-ip-address: false
#  client:
#    service-url:
#      defaultZone: http://server1:8000/eureka, http://server2:8001/eureka
